language: python
cache: pip
python:
  - 3.6
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y feh conky
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source='.' -m py.test -vv --runslow
  - coverage report -m
after_success:
  - coveralls
deploy:
  provider: pypi
  user: jakobgm
  password:
    secure: G84gKVBTjQzm3kLc4VkyQwKL2MY9PSm9Yp6O1Q/FxaBzw5v+P8MGcljwwri0iRc3jppfsuoUFegFHmKg3ufNGINTlVPvSQBIm/UyMxsLgu7BV8aQK5o2E5XN/Q3ET4MlIz7Qpypy8iBs3omNRD+pgSgyRmkk2XOufMw+C9cSM+4udCrXE2HA+4mJVXNs63rmtLCwRQDJ/C5+LtwycuoyZeIvIwrOS9G/PtauUZu+Qv/KmRan7kwaC4zNJHw5GVGsUJ0ozj1PwQJ1uL/+Gb0oUiCWe1m79+XLDtiBgVwQmBeVO9flxJIET5ggZ/Vyku/6qidovMzkiVxX9bkoFd4dU7aFpD7SE8pHpWIguVnYhDE0Xzw3C0JxfUNDGKDPbWRgTzCyMWlTUTqxgXB2/CSaATGZ/DbVR5OBdQwPVF/+qKANxvtpSnJr4NhfjreK4zJ0q32hLz19KOH62yHZNeo7U0Z8EMx6JMPLYFv1FI+WZStkj0JrFJfQ/zG7PRUE2iuE4CXnh5egaRF/jmPsrm/Qljstz/PHtxHuETOxgUyRViscN+XtdCMimqFFKy7CV+kYc9ZzIRqRBa5KHEcMg7kqN5C8hs6ETVHpIAyp2XBeiX5NsJE+vnd0HHj0a7F1KEfz2pflORBnpfU8iz2dpDiMYfRQx1W3wDwuhnJNtMVJ/4g=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
